### ISSUE TITLE
Are the labels in training data should be numeric?

### ISSUE THREAD

**Issue by gaospecial** [feranick/SpectralMachine#2]
I have transform my input to what is seen like example, which is:

```
0  1000  1001  1002  1003 ...
lab1  123 140  180  150  ...
lab2 ... ... ... ... ...
```

However, when I run the program, it failed with:

```
  Opening learning file:  rnd.txt
 Learning file not found
```

By contrast, if I remove the letter in label, and transform the input to:

```
0  1000  1001  1002  1003 ...
1  123 140  180  150  ...
2 ... ... ... ... ...
```

It can run successfully.

```
  Opening learning file:  rnd.txt
  Normalizing spectra between 0 and 1
  Total number of points per data: 501
  Number of learning labels: 1

  Number unique classes (training):  10

  Label Encoder saved in: ./model_le.pkl 
```

So, are the labels in training data should be numeric?

**Comment by feranick** [comment]
Yes, labels need to be numeric. I'd recommend creating a script/tables that may convert your labels to a numeric value.

**Comment by feranick** [comment]
This might give you some inspiration on how to create a Training file (in this case from a library of spectra from Rruff), as well as a Summary file with the alphanumeric labels. Essentially, a table with the numeric classes used in the training files and their corresponding labels. 

https://github.com/feranick/SpectralMachine/blob/master/Utilities/RruffDataMaker.py
